-- reviews.id 컬럼이 IDENTITY(자동 생성) 속성을 잃어버려 리뷰 작성 시
-- Hibernate가 AssertionFailure: null identifier (com.Wavey.WaveyService.domain.review.entity.Review)로 실패하던 문제 복구.
-- 확인 결과 reviews.id만 is_identity=NO, column_default=NULL (다른 테이블은 정상).
-- 현재 최대 id(10) 이후부터 채번되도록 identity를 다시 걸고 시퀀스를 맞춘다.

ALTER TABLE reviews ALTER COLUMN id SET NOT NULL;

ALTER TABLE reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE reviews ALTER COLUMN id RESTART WITH 11;
