-- =============================================================================
-- WAVEY content media schema (YouTube / Spotify)
-- Target: wavey_db (Docker postgres / local)
--
-- YouTube : content_videos 유지 + 유니크 보강
-- Spotify : content_albums 추가 + content_tracks 앨범 소속(nullable) + 컬럼명 정리
--
-- UI:
--   1) albums 목록
--   2) album → tracks
--   3) track 임베드 / 링크 폴백
--   4) content_album_id IS NULL → 단독 트랙
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. content_albums (신규)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS content_albums (
    content_album_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    content_id       BIGINT                         NOT NULL,
    spotify_album_id VARCHAR(64)                    NOT NULL,
    title            VARCHAR(255)                   NOT NULL,
    image_url        VARCHAR(500),
    spotify_url      VARCHAR(500),
    hidden           BOOLEAN                        NOT NULL DEFAULT FALSE,
    fetched_at       TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_content_albums_content_spotify UNIQUE (content_id, spotify_album_id)
);

-- 이전 초안(album_title)이 있으면 title로 정리
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'content_albums' AND column_name = 'album_title'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'content_albums' AND column_name = 'title'
    ) THEN
        ALTER TABLE content_albums RENAME COLUMN album_title TO title;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_content_albums_content_id
    ON content_albums (content_id);

-- -----------------------------------------------------------------------------
-- 2. content_tracks 개편
-- -----------------------------------------------------------------------------
ALTER TABLE content_tracks
    ADD COLUMN IF NOT EXISTS content_album_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_content_tracks_content_album'
    ) THEN
        ALTER TABLE content_tracks
            ADD CONSTRAINT fk_content_tracks_content_album
            FOREIGN KEY (content_album_id)
            REFERENCES content_albums (content_album_id)
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_content_tracks_content_id
    ON content_tracks (content_id);

CREATE INDEX IF NOT EXISTS idx_content_tracks_content_album_id
    ON content_tracks (content_album_id);

-- spotify_id → spotify_track_id
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'content_tracks' AND column_name = 'spotify_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'content_tracks' AND column_name = 'spotify_track_id'
    ) THEN
        ALTER TABLE content_tracks RENAME COLUMN spotify_id TO spotify_track_id;
    END IF;
END $$;

-- name → title
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'content_tracks' AND column_name = 'name'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'content_tracks' AND column_name = 'title'
    ) THEN
        ALTER TABLE content_tracks RENAME COLUMN name TO title;
    END IF;
END $$;

-- 앨범 메타는 content_albums로 이관
ALTER TABLE content_tracks DROP COLUMN IF EXISTS album_name;

-- 임베드 중심 UX: preview_url 미사용
ALTER TABLE content_tracks DROP COLUMN IF EXISTS preview_url;

-- 유니크: (content_id, spotify_track_id)
ALTER TABLE content_tracks DROP CONSTRAINT IF EXISTS uk_content_tracks_content_spotify;
ALTER TABLE content_tracks DROP CONSTRAINT IF EXISTS uk_work_tracks_work_spotify;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON c.conrelid = t.oid
        WHERE t.relname = 'content_tracks'
          AND c.conname = 'uk_content_tracks_content_spotify_track'
    ) THEN
        ALTER TABLE content_tracks
            ADD CONSTRAINT uk_content_tracks_content_spotify_track
            UNIQUE (content_id, spotify_track_id);
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 3. content_videos 유니크 보강 (컬럼 변경 없음)
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_content_videos_content_id
    ON content_videos (content_id);

ALTER TABLE content_videos DROP CONSTRAINT IF EXISTS uk_work_videos_work_youtube;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON c.conrelid = t.oid
        WHERE t.relname = 'content_videos'
          AND c.conname = 'uk_content_videos_content_youtube'
    ) THEN
        ALTER TABLE content_videos
            ADD CONSTRAINT uk_content_videos_content_youtube
            UNIQUE (content_id, youtube_video_id);
    END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 4. legacy Work 테이블 제거 (content_* 로 이전 완료, 데이터 0건)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS work_tracks;
DROP TABLE IF EXISTS work_videos;
DROP TABLE IF EXISTS works;

COMMIT;

-- =============================================================================
-- 최종 스키마 요약
--
-- content_videos
--   content_video_id, content_id, youtube_video_id, title,
--   channel_title, thumbnail_url, duration_sec, hidden, fetched_at,
--   created_at, updated_at
--   UNIQUE (content_id, youtube_video_id)
--
-- content_albums
--   content_album_id, content_id, spotify_album_id, title,
--   image_url, spotify_url, hidden, fetched_at, created_at, updated_at
--   UNIQUE (content_id, spotify_album_id)
--
-- content_tracks
--   content_track_id, content_id, content_album_id(NULL 가능),
--   spotify_track_id, title, artist_name, image_url, duration_ms, spotify_url,
--   hidden, fetched_at, created_at, updated_at
--   UNIQUE (content_id, spotify_track_id)
--   FK content_album_id → content_albums (ON DELETE SET NULL)
-- =============================================================================
